services:
  video2x:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TZ=Asia/Shanghai
    ports:
      - "7863:7863"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    devices:
      - nvidia.com/gpu=all
    security_opt:
       - label=disable
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
    command: ["sleep", "infinity"]
